set(command "/home/ubuntu/cmake-3.17.0-rc1-Linux-x86_64/bin/cmake;-P;/home/ubuntu/suliang_git/PaddleX-release-2.0.0/deploy/cpp/build/ext/yaml-cpp/src/ext-yaml-cpp-stamp/download-ext-yaml-cpp.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/home/ubuntu/cmake-3.17.0-rc1-Linux-x86_64/bin/cmake;-P;/home/ubuntu/suliang_git/PaddleX-release-2.0.0/deploy/cpp/build/ext/yaml-cpp/src/ext-yaml-cpp-stamp/verify-ext-yaml-cpp.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/home/ubuntu/cmake-3.17.0-rc1-Linux-x86_64/bin/cmake;-P;/home/ubuntu/suliang_git/PaddleX-release-2.0.0/deploy/cpp/build/ext/yaml-cpp/src/ext-yaml-cpp-stamp/extract-ext-yaml-cpp.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
